services:

  clientes-db:
    image: postgres:18
    container_name: clientes-db
    environment:
      POSTGRES_DB: tienda_clientes
      POSTGRES_USER: clientes_app
      POSTGRES_PASSWORD: clientes123
    volumes:
      - clientes_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clientes_app -d tienda_clientes"]
      interval: 5s
      timeout: 5s
      retries: 10

  clientes-service:
    build: ./clientes-service
    container_name: clientes-service
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql+psycopg2://clientes_app:clientes123@clientes-db:5432/tienda_clientes
    depends_on:
      clientes-db:
        condition: service_healthy

  zapatos-db:
    image: postgres:18
    container_name: zapatos-db
    environment:
      POSTGRES_DB: tienda_zapatos
      POSTGRES_USER: zapatos_app
      POSTGRES_PASSWORD: zapatos123
    volumes:
      - zapatos_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zapatos_app -d tienda_zapatos"]
      interval: 5s
      timeout: 5s
      retries: 10

  zapatos-service:
    build: ./zapatos-service
    container_name: zapatos-service
    ports:
      - "8002:8002"
    environment:
      DATABASE_URL: postgresql+psycopg2://zapatos_app:zapatos123@zapatos-db:5432/tienda_zapatos
    depends_on:
      zapatos-db:
        condition: service_healthy

volumes:
  clientes_data:
  zapatos_data:
